import { writeFileSync } from "node:fs";
import { textDecoderLabels } from "../packages/compiler/src/frontend/lowering/text-decoder-encoding.js";

writeFileSync(
  new URL("../packages/runtime/src/scr_text_decoder_labels.h", import.meta.url),
  [
    "/* Generated by scripts/gen-text-decoder-labels.mts. Do not edit by hand. */",
    "static const struct { const char *label; int encoding; } scr_td_labels[] = {",
    ...textDecoderLabels.map(([label, encoding]) => `  {${JSON.stringify(label)}, ${encoding}},`),
    "};",
    "",
  ].join("\n"),
);
